# Generated by Django 3.1.1 on 2020-09-20 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Buy_Price',
            new_name='buy_Price',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Quantity',
            new_name='quantity',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Sell_Price',
            new_name='sell_Price',
        ),
    ]
