# Generated by Django 3.1.1 on 2020-09-20 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200920_0555'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vendor_Purchase',
            new_name='Vendor_Order',
        ),
    ]
