# Generated by Django 3.1.1 on 2020-09-20 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200920_0701'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor_order',
            name='product',
        ),
        migrations.RemoveField(
            model_name='vendor_order',
            name='vendor',
        ),
        migrations.DeleteModel(
            name='Client_Order',
        ),
        migrations.DeleteModel(
            name='Vendor_Order',
        ),
    ]
