# Generated by Django 3.1.1 on 2020-09-20 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_vendor_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product_request',
            old_name='Quantity',
            new_name='quantity',
        ),
        migrations.AddField(
            model_name='client_order',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='vendor_order',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
    ]
